// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhdl4jM3oscHGb9c4QEvVwhZHls35Oufk',
    appId: '1:751533369230:web:1df05caaf929d6bbb826df',
    messagingSenderId: '751533369230',
    projectId: 'mental-health-3-edcc7',
    authDomain: 'mental-health-3-edcc7.firebaseapp.com',
    storageBucket: 'mental-health-3-edcc7.firebasestorage.app',
    measurementId: 'G-Z89L8LQHEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC35chyx8gPdiFQmLD194CF-3EOpGSSEL0',
    appId: '1:751533369230:android:08653d75359fc85cb826df',
    messagingSenderId: '751533369230',
    projectId: 'mental-health-3-edcc7',
    storageBucket: 'mental-health-3-edcc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-LoBOBlhZQE73Eg_hObFDlDr0jjD8jc8',
    appId: '1:751533369230:ios:7ac3388e3a57e020b826df',
    messagingSenderId: '751533369230',
    projectId: 'mental-health-3-edcc7',
    storageBucket: 'mental-health-3-edcc7.firebasestorage.app',
    androidClientId: '751533369230-76ttj1vnkicei8663ou7ocian53afvep.apps.googleusercontent.com',
    iosClientId: '751533369230-7g2l4is7j1h0of6sfmauca18rdfdl5iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.animatedCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-LoBOBlhZQE73Eg_hObFDlDr0jjD8jc8',
    appId: '1:751533369230:ios:7ac3388e3a57e020b826df',
    messagingSenderId: '751533369230',
    projectId: 'mental-health-3-edcc7',
    storageBucket: 'mental-health-3-edcc7.firebasestorage.app',
    androidClientId: '751533369230-76ttj1vnkicei8663ou7ocian53afvep.apps.googleusercontent.com',
    iosClientId: '751533369230-7g2l4is7j1h0of6sfmauca18rdfdl5iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.animatedCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhdl4jM3oscHGb9c4QEvVwhZHls35Oufk',
    appId: '1:751533369230:web:a60294e97b3070deb826df',
    messagingSenderId: '751533369230',
    projectId: 'mental-health-3-edcc7',
    authDomain: 'mental-health-3-edcc7.firebaseapp.com',
    storageBucket: 'mental-health-3-edcc7.firebasestorage.app',
    measurementId: 'G-Y370H4M32C',
  );

}